name: VoiceReader
options:
  bundleIdPrefix: com.moonlitpsych
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: false

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"  # iPhone only

targets:
  VoiceReader:
    type: application
    platform: iOS
    sources:
      - path: VoiceReader
        excludes:
          - "*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.moonlitpsych.voicereader
        INFOPLIST_FILE: VoiceReader/Info.plist
        CODE_SIGN_ENTITLEMENTS: VoiceReader/VoiceReader.entitlements
        GENERATE_INFOPLIST_FILE: true
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: true
    dependencies:
      - target: VoiceReaderShareExtension
        embed: true

  VoiceReaderShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: VoiceReaderShareExtension
        excludes:
          - "*.entitlements"
      # Shared files that both targets need
      - path: VoiceReader/Shared/AppGroupConstants.swift
      - path: VoiceReader/Shared/SharedModelContainer.swift
      - path: VoiceReader/Models/Clip.swift
      - path: VoiceReader/Engine/TextProcessor.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.moonlitpsych.voicereader.share-extension
        INFOPLIST_FILE: VoiceReaderShareExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: VoiceReaderShareExtension/VoiceReaderShareExtension.entitlements
        GENERATE_INFOPLIST_FILE: true
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: true
